name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: vesno4null
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Generate snake animation'
          commit_options: '--no-verify'
          file_pattern: dist/
          branch: output
